"""Added update date

Revision ID: 1edf17bb8244
Revises: 
Create Date: 2021-07-17 11:27:44.731885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edf17bb8244'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.add_column('packages', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_packages_updated_date'), 'packages', ['updated_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packages_updated_date'), table_name='packages')
    op.drop_column('packages', 'updated_date')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###
