"""add create and update time

Revision ID: 2dd048d1d2e8
Revises: 1edf17bb8244
Create Date: 2021-07-28 10:11:46.326980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd048d1d2e8'
down_revision = '1edf17bb8244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_users_create_date'), 'users', ['create_date'], unique=False)
    op.create_index(op.f('ix_users_updated_date'), 'users', ['updated_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_updated_date'), table_name='users')
    op.drop_index(op.f('ix_users_create_date'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
