"""define date field better

Revision ID: da9ec307e48a
Revises: 2dd048d1d2e8
Create Date: 2021-08-01 12:57:46.720455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9ec307e48a'
down_revision = '2dd048d1d2e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
